# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI2.0.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from detect import run, parse_opt2, main
# from utils.dataloaders import LoadStreams
import cv2
from PyQt5.QtGui import QImage, QPixmap
from PyQt5.QtWidgets import QLabel, QMainWindow, QApplication, QVBoxLayout, QWidget
from PyQt5.QtCore import Qt, QTimer
import sys


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1960, 1055)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1960, 1080))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.frame.setFont(font)
        self.frame.setAutoFillBackground(False)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(720, 770, 441, 111))
        self.pushButton.setObjectName("pushButton")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(920, 420, 261, 181))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.widget = QtWidgets.QWidget(self.frame_2)
        self.widget.setGeometry(QtCore.QRect(10, 10, 244, 48))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox = QtWidgets.QCheckBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.checkBox.setFont(font)
        self.checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox.setAutoFillBackground(False)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_2.addWidget(self.checkBox)
        self.checkBox_3 = QtWidgets.QCheckBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout_2.addWidget(self.checkBox_3)
        self.widget1 = QtWidgets.QWidget(self.frame_2)
        self.widget1.setGeometry(QtCore.QRect(11, 121, 244, 48))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_2 = QtWidgets.QCheckBox(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout.addWidget(self.checkBox_2)
        self.checkBox_4 = QtWidgets.QCheckBox(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setObjectName("checkBox_4")
        self.horizontalLayout.addWidget(self.checkBox_4)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(570, 470, 281, 81))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(680, 130, 481, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(34)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")


        self.retranslateUi(Form)
        # self.load_streams = LoadStreams()
        # self.is_detecting=True
        # self.pushButton.clicked.connect(lambda: self.detectYolo(s))
        self.pushButton.clicked.connect(self.onButtonClick)
        # self.pushButton_2.clicked.connect(self.pause_detection)
        # self.pushButton_3.clicked.connect(self.continue_detection)
        # print(s)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "AI坯布瑕疵检测系统1.0"))
        self.pushButton.setText(_translate("Form", "开始检测"))
        self.checkBox.setText(_translate("Form", "抽丝0"))
        self.checkBox_3.setText(_translate("Form", "污渍2"))
        self.checkBox_2.setText(_translate("Form", "破洞1"))
        self.checkBox_4.setText(_translate("Form", "毛疵3"))
        self.label.setText(_translate("Form", "选择要检测的瑕疵种类"))
        self.label_2.setText(_translate("Form", "AI坯布瑕疵检测系统1.0"))

    def getCheckboxStates(self):
        # 获取四个checkbox按钮的状态
        state0 = 1 if self.checkBox.isChecked() else 0
        state1 = 1 if self.checkBox_2.isChecked() else 0
        state2 = 1 if self.checkBox_3.isChecked() else 0
        state3 = 1 if self.checkBox_4.isChecked() else 0
        listState = [state0, state1, state2, state3]
        print(listState)
        return listState

    def onButtonClick(self):

        checkbox_states = self.getCheckboxStates()
        self.detectYolo(checkbox_states)

    def detectYolo(self, list):
        opt = parse_opt2(list[0], list[1], list[2], list[3])
        main(opt)









